export const AUTH_SUCCES ="AUTH_SUCCES";
export const AUTH_FAIL ="AUTH_FAIL";
export const REGISTER_SUCCES ="REGISTER_SUCCES";
export const REGISTER_FAIL ="REGISTER_FAIL";
export const LOGIN_SUCCES ="LOGIN_SUCCES";
export const LOGIN_FAIL ="LOGIN_FAIL";
export const LOGOUT_SUCCES ="LOGOUT_SUCCES";
export const LOGOUT_FAIL ="LOGOUT_FAIL";
export const USER_LOADING ="USER_LOADING";
export const USER_LOADED ="USER_LOADED";

export const GET_FRIEND_SUCESS="GET_FRIEND_SUCESS"
export const GET_FRIEND_FAIL="GET_FRIEND_FAIL"

export const DELETE_USER_SUCCES="DELETE_USER_SUCCES";
export const DELETE_USER_FAIL="DELETE_USER_FAIL";