export const USER_POST_SCUSESS="USER_POST_SCUSESS";
export const USER_POST_FAIL="USER_POST_FAIL";
export const USERTIMELINE_POSTS_SCUSESS="USERTIMELINE_POSTS_SCUSESS";
export const USERTIMELINE_POSTS_FAIL="USERTIMELINE_POSTS_FAIL";

export const POSTED_USER_SUCESS="POSTED_USER_SUCESS";
export const POSTED_USER_FAIL="POSTED_USER_FAIL";

export const LOADING_USER="LOADING_USER";
export const LOADING_POSTS="LOADING_POSTS";

export const FRIEND_POSTS_SUCESS="FRIEND_POSTS_SUCESS";
export const FRIEND_POSTS_FAIL="FRIEND_POSTS_FAIL";